import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "../components/molecules/navbar";
import BottomNav from "../components/molecules/bottom-nav";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // kamu bisa sesuaikan dengan kebutuhan
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Navbar/>
        {children}
        <BottomNav/>
      </body>
    </html>
  );
}
